<?php
namespace ybs\cli;
use ybs\cli\err_handle;

if (!defined('cli'))
    exit('No direct script access allowed');

require_once  "err_handle.php";



class mvc extends err_handle{
	

	

	
public function create_controller($path,$ltv,$ltm){
	$path = str_replace(" ","_",$path);
	$path = str_replace(".","_",$path);
	$path = str_replace(",","_",$path);
	echo "--------------------\n";
	echo "create controller...\n";
	$dp = explode("/",$path);
	
	$cdp = count($dp);
	switch($cdp){
		case 1:
			$success = $this->single_c(ucfirst($dp[0]),"",$ltv,$ltm);
			if($success){
				echo "path       : ./application/controllers/$dp[0].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage(). "\n";
			}	
		break;
		
		case 2:
			$success = $this->single_c(ucfirst($dp[1]),"$dp[0]/",$ltv,$ltm);
			if($success){
				echo "path       : ./application/controllers/$dp[0]/$dp[1].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage(). "\n";
			}		
		break;
		default:
		echo "failed..! not valid..!\n". $path;
		echo "--------------------\n";
		return;
	}

	
}

public function create_model($path){
	$path = str_replace(" ","_",$path);
	$path = str_replace(".","_",$path);
	$path = str_replace(",","_",$path);
	
	echo "--------------------\n";
	echo "create model...\n";
	$dp = explode("/",$path);
	
	$cdp = count($dp);
	switch($cdp){
		case 1:
			$success = $this->single_m(ucfirst($dp[0])."_model","application/models");
			if($success){
				echo "path       : ./application/models/$dp[0].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage(). "\n";
			}
		break;
		
		case 2:
			$success = $this->single_m(ucfirst($dp[1])."_model","application/models/$dp[0]");
			if($success){
				echo "path       : ./application/models/$dp[0]/$dp[1].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage(). "\n";
			
			}
		break;
		default:
		echo "failed..! not valid..!\n". $path;
		echo "--------------------\n";
		return;
	}

	
}


public function create_view($path){
	$path = str_replace(" ","_",$path);
	$path = str_replace(".","_",$path);
	$path = str_replace(",","_",$path);
	
	echo "--------------------\n";
	echo "create view...\n";
	$dp = explode("/",$path);
	
	$cdp = count($dp);
	switch($cdp){
		case 1:
			$success = $this->single_v(ucfirst($dp[0])."_view","application/views");
			if($success){
				echo "path       : ./application/views/$dp[0].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage(). "\n";
			}
			
		break;
		
		case 2:
			$success = $this->single_v(ucfirst($dp[1])."_view","application/views/$dp[0]");
			if($success){
				echo "path       : ./application/views/$dp[0]/$dp[1].php \n" ;
				echo "success..\n" ;
			}else{
				echo $this->getErrorMessage() . "\n";
			}
		break;
		default:
		echo "failed..! not valid..!\n". $path;
		echo "--------------------\n";
		return;
	}
	
	
}

private function single_c($cname,$path,$ltv=false,$ltm=false){
$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class $cname extends CI_Controller {
	
   function __construct(){
        parent::__construct();";
if($ltm){
$string .="
		\$this->load->model('$path$cname"."_model"."','tmodel');";
}
$string.="
   }
   
   
   function index(){
";
if($ltv){
$string .="
		\$d = array();
		\$d['title_page_big'] = 'New Page Blank';
		\$this->template->load('$path$cname"."_view"."',\$d);";

}

$string .="	  
	   
   }
   
   
   
   
   
   
   
}








/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CLI ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/


";


return $this->_createFile($string,"application/controllers/".$path,$cname .".php" );	
}


private function single_m($cname,$path){
$string = "<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class $cname extends CI_Model {
   public \$id;
   function __construct(){
        parent::__construct();
   }
   
   
   
   
   
   
   
   
   
   
}








/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CLI ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/


";


return  $this->_createFile($string,$path,$cname .".php" );	
}	


private function single_v($cname,$path){
$string = "
Hii,,,ini blank view
  
";


return  $this->_createFile($string,$path,$cname .".php" );	
}





function _createFile($string, $path_file,$file_name){
	
	$this->open_error_trap();
	
	$path_file = trim($path_file, '/');
	
	

	try{
		
		$system = array(
					'application/controllers/sistem',
					'application/models/sys',
					'application/views/sistem',
					);
		$file_system = array(
					'application/controllers/auth.php',
					'application/controllers/home.php',
					'application/controllers/service_storage.php',
					'application/controllers/service_upload.php',
					'application/controllers/ybsservice.php',
					'application/controllers/api/public_access.php',
					);			
		
		$pass=false;
		
		
			
		foreach($system as $val){
			if(strpos(strtolower($path_file),$val) !== false){
				$pass=true;
			}
			
		}				
		
		if($pass==true){
			$this->setErrorMessage("ERROR..can't use path :" . $path_file ."\nFailed ! (path system) ");
			
			return false;
		}
		
		
		
		
		$pass=false;	
		$pfile = strtolower($path_file .'/'.$file_name);

		foreach($file_system as $val){
			if(strpos($pfile,$val) !== false){
				$pass=true;
			}
			
		}				
		
		if($pass==true){
			$this->setErrorMessage("ERROR..can't use path :" . $pfile ."\nFailed ! (file system) ");
			
			return false;
		}
			
			
			
			
		

		
		if (!file_exists($path_file)){
            mkdir($path_file, 0777, true);
		}
	
	
		if(file_exists($path_file .'/'.$file_name)){
			echo "file already exist..! , Overwrite file?(y/n)";
			$handle = fopen("php://stdin","r");
			$in = trim(fgets($handle));	
			if(strtolower($in)=="y"){
					$create = fopen($path_file .'/'.$file_name, "w") or die("Change your permision folder for application  to 777");
					fwrite($create, $string);
					fclose($create);
					return true;
			}else{
				$this->setErrorMessage('failed create file');
				return false;
			}

		}else{
			$create = fopen($path_file .'/'.$file_name, "w") or die("Change your permision folder for application  to 777");
			fwrite($create, $string);
			fclose($create);
		}
	
		
	
	}catch(Exception $e){
			$this->setErrorMessage('your command not valid..!'.$e);
			return false;
	}
   
   $this->open_error_trap();
    
    return true;
}
	
	
	
}