<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_WebHook_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_bot_telegram_webhook_id	= 'ID';
		$this->sys_bot_telegram_webhook_id_service	= 'SERVICE';
		$this->sys_bot_telegram_webhook_id_bot	= 'BOT';
		$this->tservice_id	= 'TSERVICE_ID';

		$this->tservice_name	= 'SERVICE';
		$this->tservice_key	= 'KEY';
		$this->tbot_id	= 'TBOT_ID';
		$this->tbot_name	= 'BOT NAME';
		$this->tbot_token	= 'TOKEN';
		$this->tbot_chat_id	= 'CHAT_ID';
		
		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_id_service	= 'id_service';
		$this->f_id_bot	= 'id_bot';
		$this->f_tservice_id	= 'tservice_id';
	
		$this->f_name	= 'name';
		$this->f_key	= 'key';
		$this->f_tbot_id	= 'tbot_id';
		$this->f_tbot_name	= 'tbot_name';
		$this->f_token	= 'token';
		$this->f_chat_id	= 'chat_id';
		$this->f_start	= 'start';
		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_bot_telegram_webhook_id,
			//$this->f_id_service	=> $this->sys_bot_telegram_webhook_id_service,
			//$this->f_id_bot	=> $this->sys_bot_telegram_webhook_id_bot,
			//$this->f_tservice_id	=> $this->tservice_id,
			$this->f_name	=> $this->tservice_name,
			$this->f_tbot_name	=> $this->tbot_name,
			
			//$this->f_start => "START",
			//$this->f_key	=> $this->tservice_key,
			//$this->f_tbot_id	=> $this->tbot_id,
			
			//$this->f_token	=> $this->tbot_token,
			//$this->f_chat_id	=> $this->tbot_chat_id,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-12-22 21:04:07 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

