<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_Service_CMD_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_bot_telegram_service_cmd_id	= 'ID';
		$this->sys_bot_telegram_service_cmd_name	= 'COMMAND NAME';
		$this->sys_bot_telegram_service_cmd_descriptions	= 'DESCRIPTIONS';
		$this->sys_bot_telegram_service_cmd_message	= 'OUTPUT MESSAGE';
		$this->sys_bot_telegram_service_cmd_id_service	= 'ID_SERVICE';
		$this->tservice_id	= 'TSERVICE_ID';
	
		$this->tservice_name	= 'SERVICE NAME';
		$this->tservice_key	= 'KEY';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_name	= 'name';
		$this->f_descriptions	= 'descriptions';
		$this->f_message	= 'message';
		$this->f_id_service	= 'id_service';
		$this->f_tservice_id	= 'tservice_id';
	
		$this->f_tservice_name	= 'tservice_name';
		$this->f_key	= 'key';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
		$this->f_tservice_name	=> $this->tservice_name,
			//$this->f_id	=> $this->sys_bot_telegram_service_cmd_id,
			$this->f_name	=> $this->sys_bot_telegram_service_cmd_name,
			$this->f_descriptions	=> $this->sys_bot_telegram_service_cmd_descriptions,
			$this->f_message	=> $this->sys_bot_telegram_service_cmd_message,
			//$this->f_id_service	=> $this->sys_bot_telegram_service_cmd_id_service,
		//	$this->f_tservice_id	=> $this->tservice_id,
		
			
		//	$this->f_key	=> $this->tservice_key,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-12-18 05:31:34 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

