<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_regbot_telegram_id	= 'ID';
		$this->sys_regbot_telegram_name	= 'NAME';
		$this->sys_regbot_telegram_token	= 'TOKEN';
		$this->sys_regbot_telegram_chat_id	= 'CHAT ID';
		

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_name	= 'name';
		$this->f_token	= 'token';
		$this->f_chat_id	= 'chat_id';
		

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_regbot_telegram_id,
			$this->f_name	=> $this->sys_regbot_telegram_name,
			$this->f_token	=> $this->sys_regbot_telegram_token,
			$this->f_chat_id	=> $this->sys_regbot_telegram_chat_id,
			
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-12-05 13:10:23 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

