<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Register_ip_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_maintenance_ip_id	= 'ID';
		$this->sys_maintenance_ip_ip_address	= 'IP_ADDRESS';

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_ip_address	= 'ip_address';

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
			//$this->f_id	=> $this->sys_maintenance_ip_id,
			$this->f_ip_address	=> $this->sys_maintenance_ip_ip_address,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-08-14 19:54:50 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

