<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_dashboard extends CI_Controller
{


   function __construct(){
        parent::__construct();
	 } 


	/*	SET TITLE FORM
	* Mengset title form read,update,create,list.
	*/
	

    public function index(){
		
	}
	
	public function change($token){
		if($this->_token == $token){
			$data = $this->input->post('data_ajax',true);
			$val = json_decode($data,TRUE);

			$this->load->model('sys/Sys_dashboard_model','model');
			
			$d = new Outputview();
			if($val['select']=='1'){
				$this->model->save_to_dashboard($val['idform'],$this->_user_id);
				$d->success		= 'true';
				$d->message 	= 'di setting ke dashboard';
				
			}else{
				$this->model->remove_to_dashboard($this->_user_id);
				$d->success	 = 'true';
				$d->message = 'remove dari dashboard';
				
			}
			
			echo $d->result();
		}else{
			redirect('Auth');
		}
	}

}

/* End of file Sys_firstview.php */
/* Location: ./application/controllers/Sys_firstview.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-18 00:38:20 */
/* http://harviacode.com */