<?php
require APPPATH . 'controllers/sistem/General_title.php';
if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_Log_config {
	


   function __construct(){
	   /* title */
	    $this->general		= new General_title();
		$this->sys_user_log_login_id	= 'ID';
	
		$this->sys_user_log_login_login_time	= 'Login Time';
		$this->sys_user_log_login_logout_time	= 'Logout Time';
		
		$this->tuser_nmuser	= 'User';
		$this->tlevel_nmlevel	= 'Level';
		

		
		
		
		/*field_alias_database db*/
		$this->f_id	= 'id';
		$this->f_login_time	= 'login_time';
		$this->f_logout_time	= 'logout_time';
		$this->f_ip = 'ip';
		$this->f_browser = 'browser';
		$this->f_os ='os';
		$this->f_nmuser	= 'nmuser';
		$this->f_nmlevel	= 'nmlevel';
		

		
		
		
		/* CONFIG FORM LIST */
		/* field_alias_database => $title */	
		$this->table_column =array(
		
			$this->f_nmuser	=> $this->tuser_nmuser,
			$this->f_login_time	=> $this->sys_user_log_login_login_time,
			$this->f_logout_time	=> $this->sys_user_log_login_logout_time,
			$this->f_ip	=> "IP",
			$this->f_browser	=> "BROWSER",
			$this->f_os	=> "OS",
			//$this->f_tlevel_id	=> $this->tlevel_id,
			$this->f_nmlevel	=> $this->tlevel_nmlevel,
			//$this->f_tlevel_opt_status	=> $this->tlevel_opt_status,
		);

	}

};









/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-11-06 22:33:12 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/

