<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_Register extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	
	public function json(){
		$this->datatables->select('
			sys_bot_telegram_register.id as id,
			sys_bot_telegram_register.name as name,
			sys_bot_telegram_register.token as token,
			sys_bot_telegram_register.chat_id as chat_id,
		');
		
		$this->datatables->from('sys_bot_telegram_register');

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'sys_bot_telegram_register.id as id',
			'sys_bot_telegram_register.name as name',
			'sys_bot_telegram_register.token as token',
			'sys_bot_telegram_register.chat_id as chat_id',
		
		);
		$this->db->select($afield);

		$this->db->order_by('sys_bot_telegram_register.id', 'ASC');
		return $this->db->get('sys_bot_telegram_register')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'sys_bot_telegram_register.id as id',
			'sys_bot_telegram_register.name as name',
			'sys_bot_telegram_register.token as token',
			'sys_bot_telegram_register.chat_id as chat_id',
		
		);
		$this->db->select($afield);

		$this->db->where('sys_bot_telegram_register.id', $id);
		$this->db->order_by('sys_bot_telegram_register.id', 'ASC');
		return $this->db->get('sys_bot_telegram_register')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_bot_telegram_register.id <>',$id);

		$q = $this->db->get_where('sys_bot_telegram_register', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_bot_telegram_register', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_bot_telegram_register.id', $id);
		$this->db->update('sys_bot_telegram_register', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('sys_bot_telegram_register.id',$data);	
			$this->db->delete('sys_bot_telegram_register');
			
			// $this->db->where_in('sys_bot_telegram_webhook.id_bot',$data);	
			// $this->db->delete('sys_bot_telegram_webhook');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-12-05 13:10:23 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
