<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bot_Telegram_Admin_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json(){
		$this->datatables->select('
			sys_bot_telegram_admin_system.id as id,
			sys_bot_telegram_admin_system.id_bot as id_bot,
			sys_bot_telegram_admin_system.name as name,
			tbot.id as tbot_id,
			tbot.name as tbot_name,
			tbot.token as token,
			tbot.chat_id as chat_id,
		');
		
		$this->datatables->from('sys_bot_telegram_admin_system');
	
		$this->datatables->join('sys_bot_telegram_register tbot','tbot.id=sys_bot_telegram_admin_system.id_bot','LEFT'); 

		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'sys_bot_telegram_admin_system.id as id',
			'sys_bot_telegram_admin_system.id_bot as id_bot',
			'sys_bot_telegram_admin_system.name as name',
			'tbot.id as tbot_id',
			'tbot.name as tbot_name',
			'tbot.token as token',
			'tbot.chat_id as chat_id',
		
		);
		$this->db->select($afield);
		$this->db->join('sys_bot_telegram_register tbot','tbot.id=sys_bot_telegram_admin_system.id_bot','LEFT'); 

		$this->db->order_by('sys_bot_telegram_admin_system.id', 'ASC');
		return $this->db->get('sys_bot_telegram_admin_system')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'sys_bot_telegram_admin_system.id as id',
			'sys_bot_telegram_admin_system.id_bot as id_bot',
			'sys_bot_telegram_admin_system.name as name',
			'tbot.id as tbot_id',
			'tbot.name as tbot_name',
			'tbot.token as token',
			'tbot.chat_id as chat_id',
		
		);
		$this->db->select($afield);
		$this->db->join('sys_bot_telegram_register tbot','tbot.id=sys_bot_telegram_admin_system.id_bot','LEFT'); 

		$this->db->where('sys_bot_telegram_admin_system.id', $id);
		$this->db->order_by('sys_bot_telegram_admin_system.id', 'ASC');
		return $this->db->get('sys_bot_telegram_admin_system')->row();
   }


	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_bot_telegram_admin_system.id <>',$id);

		$q = $this->db->get_where('sys_bot_telegram_admin_system', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_bot_telegram_admin_system', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_bot_telegram_admin_system.id', $id);
		$this->db->update('sys_bot_telegram_admin_system', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('sys_bot_telegram_admin_system.id',$data);	
	
			$this->db->delete('sys_bot_telegram_admin_system');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2020-01-16 14:35:43 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
