<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sys_dashboard_model extends CI_Model
{
	public $table = 'sys_dashboard';

    function __construct()
    {
        parent::__construct();
    }

	function get_form($user_id){
		
		$afield=array(
		 $this->table.'.id_form',
		);
		$this->db->select($afield);
		$this->db->where($this->table.'.id_user', $user_id);
		$a =  $this->db->get($this->table)->row();
		
		$b = false;
		if(!empty($a)){
			$tbl = 'sys_form';
			$bfield = array(
				$tbl . '.code',
				$tbl . '.link',
			);
			
				$this->db->select($bfield);
				$this->db->where($tbl.'.id', $a->id_form);
				$this->db->where($tbl.'.shortcut <>', '2');
				$b=$this->db->get($tbl)->row();
				
			if(empty($b)){
				$b = false;
			}
					
		}
		return $b;
	}		

	function save_to_dashboard($id_form,$user_id){
		$field = array(
			'id',
		);
		$this->db->select($field);
		$this->db->where($this->table . '.id_user',$user_id);
		$a = $this->db->get($this->table)->row();
		
		if(empty($a)){
			$afield = array(
				'id_form'		=> $id_form,
				'id_user'		=> $user_id,
			);
			$this->db->insert($this->table,$afield);
		}else{
			$afield = array(
				'id' 			=> $a->id,
				'id_form'		=> $id_form,
				'id_user'		=> $user_id,
			);
			$this->db->replace($this->table,$afield);
		}
		
	}
	
	function remove_to_dashboard($user_id){
		$this->db->where('id_user', $user_id);		
        $this->db->delete($this->table);
	}
	
	
	
	function is_dashboard($id_form,$user_id){
		$afield = array(
			'id',
		);
		$this->db->select($afield);
		$this->db->where($this->table . '.id_form',$id_form);
		$this->db->where($this->table . '.id_user',$user_id);
		$a = $this->db->get($this->table)->row();
		
		if(empty($a)){
			return false;
		}else{
			return true;
		}	
		
	}
	

	
}

/* End of file Sys_user_model.php */
/* Location: ./application/models/Sys_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-23 16:50:15 */
/* http://harviacode.com */