<?php

class Template_bot_telegram_hook extends CI_Model {

function __construct(){
      parent::__construct();
}

function create_file($file_name,$path,$name){
					  
$string = "<?php

use ybs\\telegram\WebHook;
/**
 * Service name	: $name 
 */
class $file_name extends WebHook {
	
   public \$_TEST_CODE = false;
   
   public function __construct(){
		parent::__construct();				
   }
   
   
   public function action(\$command,\$message,\$token,\$req_chat_id){
			\$this->sendMessage(\$message,\$token,\$req_chat_id);
   }
   
   
   public function test(){
	
   }
   
   
   
";

	
		
//end class		
$string .= "











};

new $file_name();


/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator ".date('Y-m-d H:i:s')." */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
"	;	
		
		
$result = _createFile($string,$path,$file_name .'.php');		
return $result;		
		
}	
	
	
	
}	