<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_Log_detail_model extends CI_Model {
   public $id;	
   function __construct(){
        parent::__construct();
   }	
	
	public function json($id){
		$this->datatables->select('
			sys_user_log_accessuri.id as id,
			sys_user_log_accessuri.id_login as id_login,
			sys_user_log_accessuri.url_access as url_access,
			sys_user_log_accessuri.type_request as type_request,
			sys_user_log_accessuri.os_access as os_access,
			sys_user_log_accessuri.ip_address_access as ip_address_access,
			sys_user_log_accessuri.time_access as time_access,
		');
			$this->datatables->where('sys_user_log_accessuri.id_login',$id);
		$this->datatables->from('sys_user_log_accessuri');
	
		
		
		//mengembalikan dalam bentuk array
		$q =  json_decode($this->datatables->generate(),true);
		return $q;
	}
	

   public function get_all(){
		$afield = array(
			'sys_user_log_accessuri.id as id',
			'sys_user_log_accessuri.id_login as id_login',
			'sys_user_log_accessuri.url_access as url_access',
			'sys_user_log_accessuri.type_request as type_request',
			'sys_user_log_accessuri.os_access as os_access',
			'sys_user_log_accessuri.ip_address_access as ip_address_access',
			'sys_user_log_accessuri.time_access as time_access',
		
		);
		$this->db->select($afield);

		$this->db->order_by('sys_user_log_accessuri.id', 'ASC');
		return $this->db->get('sys_user_log_accessuri')->result_array();
   }


	public function get_by_id($id){
		$afield = array(
			'sys_user_log_accessuri.id as id',
			'sys_user_log_accessuri.id_login as id_login',
			'sys_user_log_accessuri.url_access as url_access',
			'sys_user_log_accessuri.type_request as type_request',
			'sys_user_log_accessuri.os_access as os_access',
			'sys_user_log_accessuri.ip_address_access as ip_address_access',
			'sys_user_log_accessuri.time_access as time_access',
		
		);
		$this->db->select($afield);

		$this->db->where('sys_user_log_accessuri.id', $id);
		$this->db->order_by('sys_user_log_accessuri.id', 'ASC');
		return $this->db->get('sys_user_log_accessuri')->row();
   }

   	public function get_by_idlogin($idlogin){
		$afield = array(
			'sys_user_log_accessuri.id as id',
			'sys_user_log_accessuri.id_login as id_login',
			'sys_user_log_accessuri.url_access as url_access',
			'sys_user_log_accessuri.type_request as type_request',
			'sys_user_log_accessuri.os_access as os_access',
			'sys_user_log_accessuri.ip_address_access as ip_address_access',
			'FROM_UNIXTIME(sys_user_log_accessuri.time_access,"%d %M %Y") as tanggal',
			'FROM_UNIXTIME(sys_user_log_accessuri.time_access,"%H:%i:%s") as jam',
		
		);
		$this->db->select($afield);

		$this->db->where('sys_user_log_accessuri.id_login', $idlogin);
		$this->db->order_by('sys_user_log_accessuri.id', 'ASC');
		return $this->db->get('sys_user_log_accessuri')->result();
   }
   
   
   

	/* Memastikan data yg dibuat tidak kembar/sama,
	   fungsi ini sebagai pengganti fungsi primary key dr db,
	   krn primary key sudah di gunakan untuk column id.
	   -create : id di kosongkan.
	   -update : id di isi dengan id data yg di proses.	
	*/	
	function if_exist($id,$data){
		$this->db->where('sys_user_log_accessuri.id <>',$id);

		$q = $this->db->get_where('sys_user_log_accessuri', $data)->result_array();
		
		if(count($q)>0){
			return true;
		}else{
			return false;
		}		

	

	}


	function insert($data){
	
	    /* transaction rollback */
		$this->db->trans_start();
		
		$this->db->insert('sys_user_log_accessuri', $data);		
		/* id primary yg baru saja di input*/
		$this->id = $this->db->insert_id(); 
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false
	}

	function update($id,$data){

		/* transaction rollback */
		$this->db->trans_start();

		$this->db->where('sys_user_log_accessuri.id', $id);
		$this->db->update('sys_user_log_accessuri', $data);
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
	}

	function delete_multiple($data){
		/* transaction rollback */
		$this->db->trans_start();
		
		if(!empty($data)){
			$this->db->where_in('sys_user_log_accessuri.id',$data);	
	
			$this->db->delete('sys_user_log_accessuri');
		}
		
		$this->db->trans_complete();
		return $this->db->trans_status(); //return true or false	
		
	}


};

/* END */
/* Mohon untuk tidak mengubah informasi ini : */
/* Generated by YBS CRUD Generator 2019-11-13 05:45:19 */
/* contact : YAP BRIDGING SYSTEM 		*/
/*			 bridging.system@gmail.com  */
/* 			 MAKASSAR CITY, INDONESIAN 	*/
